### ISSUE TITLE
smrt stats script execution

### ISSUE THREAD

**Issue by Saranya-Balachandran** [PacificBiosciences/pb-human-wgs-workflow-snakemake#100]
There has been an update in pysam conda, hence I am getting conflicting dependency issues with the installation versions mentioned in the pipeline. However, I am able to install these packages independently of the pipeline with the current versions  
 - datamash=1.7
  - pysam=0.19.1
When I provide the working versions in the env details I get the following error
 
mamba env create --quiet --file PacBio/.snakemake/conda/d2f264d3f26cd69fc36d2ef68a6b9754.yaml" --prefix "PacBio/.snakemake/conda/d2f264d3f26cd69fc36d2ef68a6b9754"
Output:
Encountered problems while solving:
  - package datamash-1.7-h516909a_0 is excluded by strict repo priority
  - package pysam-0.19.1-py27hc2126ed_0 requires libdeflate >=1.10,<1.11.0a0, but none of the providers can be installed

**Comment by juniper-lake** [comment]
The issue isn't that pysam has a newer version. Rather, newer snakemake versions enforce strict channel priority (see [changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id7)), which is clashing with our existing conda environment yamls. Please reinstall your main conda environment using the following code and make sure conda channel priority is set to true/flexible instead of strict. We are about to push these updated instructions in our tutorial.

```
# set conda channel priority to 'flexible'/true
conda config --set channel_priority true

# create conda environment
conda install mamba -n base -c conda-forge
conda activate base
mamba create -c conda-forge -c bioconda -n pb-human-wgs snakemake=6.15.3 lockfile=0.12.2 pysam=0.16.0.1 python=3

# activate conda environment 
conda activate pb-human-wgs
```

In the future, we will will update the channel priority in our yamls and make everything compatible with newer versions of snakemake.

**Comment by Saranya-Balachandran** [comment]
The issue has been resolved
