### ISSUE TITLE
Error in process_sample.local.sh

### ISSUE THREAD

**Issue by dppss90008** [PacificBiosciences/pb-human-wgs-workflow-snakemake#111]
Hello

I am trying the processed my own human WGS data with 
pb-human-wgs-workflow-snakemake.

The first code (process_smrtcells.local.sh) processed successfully.
However, the second code raised some error that the processed could not be started.

I saw some error messages from the log file
''' Log file of process_sample.180019.202207151713.log
Config file workflow/reference.yaml is extended by additional config specified via the command line.
Config file workflow/config.yaml is extended by additional config specified via the command line.
StopIteration in line 18 of /data1/PacBio-Human-WGS/workflow/process_sample.smk.
  File "/data1/PacBio-Human-WGS/workflow/process_sample.smk", line 91, in <module>
  File "/data1/PacBio-Human-WGS/workflow/process_sample.smk", line 18, in check_for_ml_tag
  File "pysam/libcalignmentfile.pyx", line 1854, in pysam.libcalignmentfile.AlignmentFile.__next__
Processing sample 180019 with reference GRCh38.
180019 movies available: ['m64259e_220713_052516']
'''

Any suggestions for solving this error ? 
Thanks 

CH

**Comment by dppss90008** [comment]
![image](https://user-images.githubusercontent.com/34399929/179195623-383a432a-fb25-4975-8c48-6865c8b0153c.png)

Some messages from process_smrtcells.log.
I am not sure if the the first process success or not.

**Comment by williamrowell** [comment]
It looks like `process_smrtcells` ran correctly.

I have an idea of what might be causing the problem.  Do you feel comfortable making a simple edit and testing it, because that might be faster than waiting for me to build the test case.

If so, please completely delete [line 18 of process_sample.smk](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/8a29995fd653922d75ff7d52b65f496ad14692f9/process_sample.smk#L18) and try running `process_sample.local.sh` again, following the same instructions that you followed originally.

**Comment by dppss90008** [comment]
Hi williamrowell

   Yes! process_sample.local.sh ran successfully after I commented out line 18 of the code!

Thanks !

CH

**Comment by williamrowell** [comment]
Glad that it works!  We merged this change into `develop` and `main`.
