### ISSUE TITLE
Updating plof file 

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#136]
Hello, 
I was double-checking the `config.yaml` file and I think the lof_lookup_url is out of date. Haven't gotten to where this is used, but writing issue now for future troubleshooting. 

From gnomad link is: 
https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz 

Source: https://gnomad.broadinstitute.org/downloads 

In `config.yaml`: 
lof_lookup_url: 'https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz'

Thank you, and I hope you had a happy Thanksgiving!

**Comment by williamrowell** [comment]
We tend to just download the entire resources directory instead of depend on these rules, so the rules have gone untested for a while.  I think the solution here is that we'll remove these rules and you can get these files directly from us.  Send an email and I'll point you to the ftp with the full `reference` and `resources` directories.

**Comment by lauragails** [comment]
Gotcha - I have those directories already from other coorespondance with PacBio, so I think we can close the ticket!
